### PR TITLE
Add support for authorization request to paypal

### PR DESCRIPTION
**Pull request by scudelletti**
This PR adds the authorization to the gem. After merge we'll be able to authorize payments.

### CODE REVIEW

**Comment by 304** [comment]
👍

**Comment by erichmachado** [comment]
:+1:

**Comment by iGEL** [comment]
:+1:

**Comment by paranoida** [comment]
@iGEL wait... wat?!

**Comment by scudelletti** [comment]
@paranoida Everybody loves old code man.

**Comment by solak** [comment]
👍

**Pull request merged**
